# Generated by Django 5.2.5 on 2025-08-22 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('base_currency', models.CharField(default='USDT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crypto_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.cryptopair')),
                ('buy_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_opportunities', to='arbitrage.exchange')),
                ('sell_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_opportunities', to='arbitrage.exchange')),
            ],
            options={
                'ordering': ['-profit_percentage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('crypto_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.cryptopair')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage.exchange')),
            ],
            options={
                'unique_together': {('exchange', 'crypto_pair', 'timestamp')},
            },
        ),
    ]
